#!/bin/bash

FLDR=${1:-www}				; shift

DIR_APP1="${1:-app01}"			; shift
DIR_APP2="${1:-app04_with_css}"		; shift

DIR_TEMP=$HOME/tmp

#-------------------------------------------------------------------------------
#
#-------------------------------------------------------------------------------
DEBUGLEVEL=0
function print() {
	printf "%s\n" "$1"
}

function debug() {
	LEVEL="$1"; shift
	LINE="$*"

	if [[ $LEVEL -le $DEBUGLEVEL ]]; then
		echo "DBG | $*"
	fi
}

#-------------------------------------------------------------------------------
#
#-------------------------------------------------------------------------------
function prepeare_for_diff() {
	SRC="$1"
	DST="$2"

	debug 4 "prepare $SRC"

	js-beautify "${SRC}"		|\
	grep -v "^\s*//.*" 		|\
	sed '1,$s#/\*.*\*/#@@#g'	>"${DST}"
}

#-------------------------------------------------------------------------------
TMP_SRC="$DIR_TEMP/src"
TMP_DST="$DIR_TEMP/dst"

#-------------------------------------------------------------------------------
find "$DIR_APP1/${FLDR}" "$DIR_APP2/${FLDR}" -type f | cut -d/ -f2- | sort| uniq | while read FILE
do
	debug 2 "check file $FILE"
	EXT="${FILE##*.}"

	debug 3 "check file extention"
	if [[ "|map|jpg|png|ttf|ico|svg|woff|woff2|eot|" =~ "|$EXT|" ]]; then
		debug 4 "ignore $EXT files"
		:  Ignore
	else 
		STATUS="OK"
		[ -f "$DIR_APP1/$FILE" ] && STATUS="no file for $DIR_APP1"
		[ -f "$DIR_APP2/$FILE" ] && STATUS="no file for $DIR_APP2"
		
		if [[ "$STATUS" == "OK" ]]; then
			printf "  %-40s %s\n" "$FILE" "$STATUS"
		else
			prepeare_for_diff "$DIR_APP1/$FILE" "$TMP_SRC"
			prepeare_for_diff "$DIR_APP2/$FILE" "$TMP_DST"

			DIFF="$(diff -BEw $TMP_SRC $TMP_DST)"
			RC=$?

			if [[ $RC = 0 ]]; then
				: printf "# %-40s %s\n" "$FILE" "$STATUS"
			else
				printf "* %-40s %s\n" "$FILE" "$STATUS"
				diff -BEw $TMP_SRC $TMP_DST
			fi
		fi
	fi
done
